#服务器配置
server:
  port: 8080
  servlet:
    context-path: /book
file:
  upload:
    path: D://images/

#沙箱支付参数
alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appid: 2021000119637885
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCj5dkdaLtYAFpnzQyhlkzprKD4kVEgzMli3H0ujhKP8HGdmumepQpvpC+rUSVwIiXPx/xEunI/wwFlFSTkpWA9dkjiSmOiukP3thWVH7QGBpObgtrM0PPYFx204pTMN+0MUSdF4RCHfo+5bxRmi9WDdgU6hCKkeSp4W8vsCLHYrMa82wk+KDVm5AgWNPbS8fjsZTckIGayYp+5rerXQd4UVAwdX9CwhNOR6qQZRlXUvaJjJj0ab6LolLDim5M/h/8bcLhKoooYA2RaQ//5IQZCB3O1y8KFR29j0NtpAHYfxkP8kgA5Mk6GLQchITBJ3N7Oi5OxI6s99Oq7EWgUPH2tAgMBAAECggEAD6H9yoNR0zv9Y4c4XDVE0skHdY4Oye0ejFJxkj404QvTGnBLNjmRvEJR1apgwshPCPmPQ1LxUMmd2XFh2nk3q8UbgJIN3NidYQQ6HMYwWp7H935Mtlp717GkwLsX7D6tWo5nC5BDDllxBgPlUz6lN+vK5eDymPOBrIc89R+DLyJsKZPuNhJLuyce43GkIesywZAia7LexoBLOsJ5Gfi/0ok096pZSrDhspQO/L0rTFEgUfHgvmfz8iTYRt9uN6qM2aKysB0N7j+lK2RmHwu2gF2b26rzxYgZLknRzKdXwGg84mmnhrPOsuxbPVEgvxUpAM9IDrcWFBeW5PzidWFUlQKBgQDvVPOPJtq+UBbtJJ6pVtNRoijzwRSAOskf7JT0v0C41yEW7VSCKAF3SjGFNO/Tmb56dxzlRIf/Uy4pDhEuODAz3jHsTUvlaAmx1hCnlMwZYkVc4tbDBq+CFdA6A7lrARHlTqKo6LmMm7/Hpr3tPfXmBW6VhzieSdW+DBiJOEdhFwKBgQCvT/vMaEmqI7+hP3V5sQ8av13i/UPnuLZ23wGfn3GSNFoWsVy5VpVyK+KAXpPa/2Rd5U/gsLtFoeZeuXt74HJZ/s9O7O06Mi8K5HV2zVfZ/cXEC7ns10NUNHKPMWI4TUTh8xVOsxLuR4L80bn1L3QihLWXP3Qr0z/wFvZFrrZp2wKBgAzK3qXlLsYDY+ZTEcP9Zxgy8btts5nTCpMRQzj9zAjVPuiJ0P2QA9wLdDApjzQhQKQtH7dFfXtxR8NcBCETUchD9SkrTIY7lGEUDxnWAz7MGOcJHO+ZuOHcJqAjONL2YK2AEYOzxM82N/8E85vttuoPmkSV0LntOmaJIPqcrnwLAoGAEFxCf1zsIvibFY06hVTEuBZLyLch8yoFvSoqmJ7klmRUU/HRWWp/H9yAksJAwhs7Xpfb0Hgtwd3OBeEBaRoVEdj5t7/ck6XDRhzz6VZYcHuCTT1a6INeQSlz13EgXWi4mO16e5GynpIF41ofJIZ9LAt+dtLxIHXibaF28iHP3CkCgYEAvJX9VgTucIBUTi8wgMLmPBZMeM0oSk5eGfi0KxKIqHeuJE2oBAC2SRFNm5VLYA2ncWHuLw8lrGyGrV/p0RHjBm3WIERKTPUNWvkTGGUbi0/1tkc1IVgBUFilhXbWVd2zqFUOkuBeBCnnJoCA5k5SmPo0WXSzYYZZBX5yKHpFnDs=
  publicKey:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo+XZHWi7WABaZ80MoZZM6ayg+JFRIMzJYtx9Lo4Sj/BxnZrpnqUKb6Qvq1ElcCIlz8f8RLpyP8MBZRUk5KVgPXZI4kpjorpD97YVlR+0BgaTm4LazNDz2BcdtOKUzDftDFEnReEQh36PuW8UZovVg3YFOoQipHkqeFvL7Aix2KzGvNsJPig1ZuQIFjT20vH47GU3JCBmsmKfua3q10HeFFQMHV/QsITTkeqkGUZV1L2iYyY9Gm+i6JSw4puTP4f/G3C4SqKKGANkWkP/+SEGQgdztcvChUdvY9DbaQB2H8ZD/JIAOTJOhi0HISEwSdzezouTsSOrPfTquxFoFDx9rQIDAQAB
  #公网
  notifyUrl: http://ugi3in.natappfree.cc/book/notify
  #私网
  returnUrl: http://localhost:8080/book/order/list

web:
  upload-path: D://images/
#数据库相关配置:
spring:
  devtools:
    restart:
      enabled: false #关闭热部署
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/book_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #解析resources/静态资源
  mvc:
    static-path-pattern: /**

#mybatis plus配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.book.bookshop.entity
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.book.bookshop.entity.enums
  global-config:
    #    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #    #驼峰下划线转换
    #    db-column-underline: true
    #    #mp2.3+ 全局表前缀 mp_
    #    #table-prefix: mp_
    #    #刷新mapper 调试神器
    #    #refresh-mapper: true
    #    #数据库大写下划线转换
    #    #capital-mode: true
    #    # Sequence序列接口实现类配置
    #    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #    #自定义填充策略接口实现
  #    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #     控制台打印sql
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    #    map-underscore-to-camel-case: true
    cache-enabled: true
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'